<?php
/**
 * Created by PhpStorm.
 * User: nathan
 * Date: 6/2/2018
 * Time: 9:32 PM
 */

namespace Tests\Staticize;

use Staticize\OutputBuffer;

class OutputBufferTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OutputBuffer $outputBuffer
     */
    private $outputBuffer;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->outputBuffer = new OutputBuffer();
    }

    public function testBlockEnclose()
    {
        $a = 'variable a';
        $this->outputBuffer->start();
        echo $a . PHP_EOL;
        echo 'test line';
        $this->outputBuffer->end();
        $this->assertEquals('variable a' . PHP_EOL . 'test line', $this->outputBuffer->getContent());
    }

    public function testEnclose()
    {
        $a = 'variable a';
        $this->outputBuffer->enclose(function () use ($a) {
            echo $a . PHP_EOL;
            echo 'test line';
        });
        $this->assertEquals('variable a' . PHP_EOL . 'test line', $this->outputBuffer->getContent());
    }
}
