<?php
/**
 * Created by PhpStorm.
 * User: nathan
 * Date: 2018/5/31
 * Time: 18:04
 */

namespace Tests\Refine;

use Refine\Staticize;

class StaticizeTest extends \PHPUnit_Framework_TestCase
{
    private $staticize;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->staticize = Staticize::getInstance([]);
    }

}
