<?php
/**
 * Created by PhpStorm.
 * User: nathan
 * Date: 6/1/2018
 * Time: 11:54 PM
 */

namespace Tests\Staticize\Validator;

use Staticize\Validator\ExpireValidator;

class ExpireValidatorTest extends BaseValidatorTest
{

    public function testFalseValid()
    {
        $this->page->addValidator(new ExpireValidator(1));
        $this->page->enclose(function () {
            echo '1';
        });
        sleep(2);
        $this->assertFalse($this->page->isValid());
    }

    /**
     * @depends testFalseValid
     */
    public function testTrueValid()
    {
        $this->page->addValidator(new ExpireValidator());
        $this->page->enclose(function () {
            echo '1';
        });
        $this->assertTrue($this->page->isValid());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unlink($this->file);
    }


}
