<?php
/**
 * Created by PhpStorm.
 * User: nathan
 * Date: 6/1/2018
 * Time: 11:54 PM
 */

namespace Tests\Staticize\Validator;

use Staticize\Page;
use Staticize\Validator\ModificationValidator;

class ModificationValidatorTest extends BaseValidatorTest
{

    /**
     * @var integer $mtime
     */
    private $mtime;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mtime = time();
        $this->page->setMtime($this->mtime);
    }

    public function testFalseValid()
    {
        $this->page->addValidator(new ModificationValidator($this->mtime + 100));
        $this->page->enclose(function () {
            echo '1';
        });
        sleep(2);
        $this->assertFalse($this->page->isValid());
    }

    public function testTrueValid()
    {
        $this->page->addValidator(new ModificationValidator($this->mtime));
        $this->page->enclose(function () {
            echo '1';
        });
        $this->assertTrue($this->page->isValid());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unlink($this->file);
    }


}
