<?php
/**
 * Created by PhpStorm.
 * User: nathan
 * Date: 6/3/2018
 * Time: 9:30 PM
 */

namespace Tests\Unit\Staticize;


use Staticize\OutputBuffer;

/**
 * Class OutputBufferTest
 * @package Tests\Unit\Staticize
 */
class OutputBufferTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OutputBuffer $outputBuffer
     */
    private $outputBuffer;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->outputBuffer = new OutputBuffer();
    }


    /**
     * @test
     */
    public function start_and_end()
    {
        $this->outputBuffer->start();
        echo '1';
        $this->outputBuffer->end();
        $this->assertEquals(1, $this->outputBuffer->getContent());
    }

    /**
     * @test
     */
    public function enclose()
    {
        $this->outputBuffer->enclose(function () {
            echo '1';
        });
        $this->assertEquals(1, $this->outputBuffer->getContent());
    }
}
